name: AoC 2025 CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-run-days:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Verify build tools
        run: |
          cmake --version
          ninja --version

      - name: Build and run cases
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ..
          ninja
          cd tests
          ls
          ./day1 --input day1_default.in -s
          ./day2 --input day2_default.in -s
          ./day3 --input day3_default.in -s
          ./day4 --input day4_default.in -s
          ./day5 --input day5_default.in -s
          ./day6 --input day6_default.in -s
          ./day7 --input day7_default.in -s